laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::resource('domain', 'DomainController');
Route::resource('user', 'UserController');

laravel/resources/views/content/domain-list.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="center-block" style="max-width: 600px">
        <h1 class="text-center">Domains Manager</h1>

        <br />

        <form method="post" class="panel panel-default center-block" style="padding: 10px" action="{{route('domain.store')}}">
            {{csrf_field()}}
            <div class="row">
                <div class="col-md-9">
                    <input class="form-control" name="name" type="text" placeholder="add new Domain Name, i.e google.com" required/>
                </div>
                <div class="col-md-3">
                    <button class="btn btn-success form-control">Add New</button>
                </div>
            </div>
        </form>

        <br />

        <table class="table table-striped table-hover table-responsive">
            <thead style="font-weight: bold">
                <tr>
                    <!-- <td>#</td> -->
                    <td>Domain</td>
                    <td>Records</td>
                    <td>Actions</td>
                </tr>
            </thead>
            @foreach($domains as $domain)
            <tr>
                <!-- <td>{{$domain->id}}</td> -->
                <td>{{$domain->name}}</td>
                <td>{{sizeof($domain->records)}}</td>
                <td><a href="{{route('domain.edit', $domain->id)}}">Manage</a></td>
            </tr>
            @endforeach
        </table>
    </div>

@endsection

laravel/resources/views/content/domain-manage.blade.php
@extends('layouts.dashboard')

@section('content')

    @php($newIndex = sizeof((array) $domain->records))

    <div class="center-block" style="max-width: 800px">
        <h1 class="text-center">{{strtoupper($domain->name)}} Records</h1>

        <br />

        <form method="post" class="panel panel-default center-block" action="{{route('domain.update', $domain->id)}}">
            {{csrf_field()}}
            {{method_field('put')}}
            <div class="panel-heading">
                <div class="row text-center">
                    <div class="col-md-3"><b>TYPE</b></div>
                    <div class="col-md-3"><b>NAME</b></div>
                    <div class="col-md-2"><b>TTL</b></div>
                    <div class="col-md-3"><b>VALUE</b></div>
                    <div class="col-md-1"><b>Action</b></div>
                </div>
            </div>
            <div class="panel-body" style="padding: 10px">
                @foreach($domain->records as $record)
                @php($id = $record['id'])
                    <div class="row" style="{{$id == 0 ? 'border-left: 10px solid greenyellow' : ''}}" id="record-{{str_slug($id)}}">
                        <input name="records[{{$id}}][id]" value="{{$id}}" type="hidden" />
                        <div class="col-md-3">
                            <select class="form-control" name="records[{{$id}}][type]" required>
                                <option disabled selected>Add New</option>
                                @foreach(\App\Helper\Record::types() as $tid => $text)
                                <option value="{{$tid}}" {{$tid == $record['type'] ? 'selected' : ''}}>{{$text}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-3">
                            <input class="form-control" type="text" name="records[{{$id}}][name]" value="{{$record['name']}}" required/>
                        </div>
                        <div class="col-md-2">
                            <input class="form-control" type="number" name="records[{{$id}}][ttl]" value="{{$record['ttl'] ?? 3600}}"/>
                        </div>
                        <div class="col-md-3">
                            <input class="form-control" type="text" name="records[{{$id}}][value]" value="{{$record['value'] ?? ''}}" required/>
                        </div>
                        <div class="col-md-1 {{$id === 0 ? 'hidden' : ''}}">
                            <a onclick="if(confirm('Do you really want to remove this record?')) {document.querySelector('#record-{{str_slug($id)}}').remove()} return false" href="?rm={{$record['id']}}" title="Delete"><span class="fa fa-trash fa-2x"></span></a>
                        </div>
                    </div>
                    <br />
                @endforeach
            </div>
            <div class="panel-footer">
                <div class="center-block">
                    <button class="btn btn-success">Save Records</button>
                    <a href="?purge" class="btn btn-danger" onclick="if(!confirm('Are Your sure, you need to delete this domain?!'))return false">Delete {{$domain->name}}</a>
                </div>
            </div>
        </form>

    </div>

@endsection

laravel/resources/views/content/home.blade.php
@extends('layouts.dashboard')

@section('content')

    <h1 class="text-center center-block text-muted">Welcom to dashboard</h1>

@endsection

laravel/resources/views/content/user-list.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="center-block" style="max-width: 600px">
        <h1 class="text-center">System Managers</h1>

        <br />

        <table class="table table-striped table-hover table-responsive">
            <thead style="font-weight: bold">
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Actions</td>
                </tr>
            </thead>
            @foreach($users as $user)
            <tr>
                <td>{{$user->id}}</td>
                <td>{{$user->name}}</td>
                <td><a href="{{route('user.edit', $user->id)}}">Edit</a></td>
            </tr>
            @endforeach
        </table>
    </div>

@endsection

laravel/resources/views/content/user-manage.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="center-block" style="max-width: 600px">
        <h1 class="text-center">{{isset($user) ? 'Edit A' : 'Create New'}} Manager</h1>

        <br />

        <form action="{{isset($user) ? route('user.update', $user->id) : route('user.store')}}" method="post" class="panel panel-default" style="padding: 15px">
            {{ method_field(isset($user) ? 'PUT' : 'POST') }}
            {{ csrf_field() }}
            <div class="form-group">
                <div class="row">
                    <div class="col-md-12">
                        <label>
                            <b>Name: </b>
                            <input placeholder="i.e admin, root, user1" required value="{{@$user->name}}" name="name" class="form-control"/>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-12">
                        <label>
                            <b>Password: </b>
                            <input placeholder="Password" name="password" class="form-control"/>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <button class="form-control btn btn-success">Save</button>
                    </div>
                    @if(isset($user))
                    <div class="col-md-6">
                        <a class="btn btn-danger form-control" href="{{route('user.index') . '?delete=' . $user->id}}">Delete</a>
                    </div>
                    @endif
                </div>
            </div>
        </form>
    </div>

@endsection